[env]
INCLUDE = { value = "C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.22621.0\\ucrt;C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.22621.0\\shared;C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.22621.0\\um;C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.44.35207\\include", relative = false }
CPATH = { value = "C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.22621.0\\ucrt;C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.22621.0\\shared;C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.22621.0\\um;C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.44.35207\\include", relative = false }
[target.x86_64-unknown-linux-gnu.env]
CARGO_TARGET_DIR = "target-linux"
LIBCLANG_PATH = "/lib/x86_64-linux-gnu"

[target.x86_64-pc-windows-msvc.env]
CARGO_TARGET_DIR = "target-windows"
LIBCLANG_PATH = "C:\\Program Files\\LLVM\\bin"
